version: '3'
services:
  wordpress:
    image: 'ghcr.io/wons-bhutan/govtech_astratemplates_wordpress:latest'
    environment:
      - WORDPRESS_DB_HOST=db
      - WORDPRESS_DB_NAME=theme5agencytemplate
      - WORDPRESS_DB_PASSWORD=theme5ow8eyF@938y0
      - WORDPRESS_DB_USER=agencytemplate
      - "WORDPRESS_CONFIG_EXTRA=define('WP_HOME','https://agencytemplateproduction.wonstechnology.com.');define('WP_SITEURL','https://agencytemplateproduction.wonstechnology.com');define('USE_MYSQL','1');"
    depends_on:
      - db
    volumes:
      - 'wordpress_data_agencytemplate:/var/www/html/wp-content'
  db:
    image: 'ghcr.io/wons-bhutan/govtech_astratemplates_mariadb:latest'
    volumes:
      - 'mariadb_data_agencytemplate:/var/lib/mysql'
    environment:
      - MARIADB_DATABASE=agencytemplate
      - MARIADB_PASSWORD=ow8eyF@938y0
      - MARIADB_ROOT_PASSWORD=rootow8eyF@938y0
      - MARIADB_USER=agencytemplate

volumes:
  mariadb_data_theme5agencytemplate: null
  wordpress_data_theme5agencytemplate: null